### ISSUE TITLE
Markdown object has no attribute 'render'

### ISSUE THREAD

**Issue by ReneFroger** [honza/socrates#22]
I got a problem with generating the contents of my site. When I"m in the current directory of my blog (`blog`), I call `socrates -g`, but I got this traceback. 

    (env)FranskeBauer@lInux:~/blog$ socrates -g
    Traceback (most recent call last):
    File "/home/FranskeBauer/blog/env/bin/socrates", line 87, in <module>
    main()
    File "/home/FranskeBauer/blog/env/bin/socrates", line 51, in main
    socrates.Generator(path, options.silent)
    File "/home/FranskeBauer/blog/env/local/lib/python2.7/site-packages/socrates/socrates.py", line 108, in __init__
    self.load_posts()
    File "/home/FranskeBauer/blog/env/local/lib/python2.7/site-packages/socrates/socrates.py", line 227, in load_posts
    self.posts.append(Post(p, self.SETTINGS))
    File "/home/FranskeBauer/blog/env/local/lib/python2.7/site-packages/socrates/models.py", line 170, in __init__
    super(Post, self).__init__(path, context)
    File "/home/FranskeBauer/blog/env/local/lib/python2.7/site-packages/socrates/models.py", line 30, in __init__
    self.parse()
    File "/home/FranskeBauer/blog/env/local/lib/python2.7/site-packages/socrates/models.py", line 71, in parse
    self._parse()
    File "/home/FranskeBauer/blog/env/local/lib/python2.7/site-packages/socrates/models.py", line 99, in _parse
    self.contents = self._process_contents(c)
    File "/home/FranskeBauer/blog/env/local/lib/python2.7/site-packages/socrates/models.py", line 141, in _process_contents
    html = processor.render(text)
    File "/home/FranskeBauer/blog/env/local/lib/python2.7/site-packages/socrates/processors.py", line 189, in render
    return self.md.render(text)
    AttributeError: 'Markdown' object has no attribute 'render'
    (env)FranskeBauer@lInux:~/blog$ 

When looking in `deploy/`, it's empty except media folder. And when looking in `media`, I have only one file, called `style.css`. 

How could I solve the message `AttributeError: 'Markdown' object has no attribute 'render'`?

**Comment by honza** [comment]
Can you give me a minimal example post that triggers this?

**Comment by ReneFroger** [comment]
I uploaded the markdown file which is located in my post directory. But it seems Github don't support this file, so I renamed it to `txt`-extension in order to upload it.

[2015-11-08-why-this-site-is-generated.txt](https://github.com/honza/socrates/files/31327/2015-11-08-why-this-site-is-generated.txt)

**Comment by honza** [comment]
I just published version `0.9.1` with a fix for this.

**Comment by ReneFroger** [comment]
What was the problem that caused this bug?

**Comment by honza** [comment]
The Misaka markdown library changed its API for 2.0 and it wasn't reflected in Socrates' code. I also found out that we didn't have pinned dependencies — but now we do.

Thanks for reporting :sparkles:
